#!/usr/bin/env python3
"""'Botanical Tour' series — 16 great tropical conservatories/botanical gardens into /review as PENDING.

Authentic, fact-anchored place-features that land on the plants collectors grow (aroids, epiphytes).
Placeholder heroes (the user sources real images from each garden's site during review). Dates are set
EARLIER than the rainforest series (2026-07-21) so the rainforest set stays on top on date-based surfaces;
the website listing is manifest-array-ordered and reordered separately.

    ANTHROPIC_API_KEY=... python gen_conservatory.py [slug]
"""
import sys, json, datetime as dt
import common, manifest_helpers, slop_repair
from render import render
from generate_leaf import SCHEMA

MANIFEST = common.SITE_ROOT / "the-leaf" / "manifest.json"
HERO = "/images/hero.jpg"; BODY = "/images/cta.jpg"   # placeholders, user swaps in review
CAT = "Botanical Tour"
# Dates: descending from 2026-07-20 (one day apart) so the whole series sits just BELOW the
# rainforest block (all 2026-07-21) on any date-sorted surface, in list order Kew→Bogor.
START = dt.date(2026, 7, 20)

ARTICLES = [
 {"slug":"conservatory-kew",
  "title":"Botanical Tour: Kew's Palm House & Princess of Wales Conservatory, London, UK — Where Glasshouse Botany Was Born",
  "angle":"The Royal Botanic Gardens, Kew (a UNESCO World Heritage Site since 2003) holds the largest and most diverse collection of living plants on Earth. Center the piece on two glasshouses. The Palm House (built 1844-1848, designed by architect Decimus Burton and Irish ironmaster Richard Turner) is the world's most important surviving Victorian glass-and-iron structure — its hull-like curves were engineered like an upturned ship to hold a tropical rainforest of palms and cycads (including the Eastern Cape giant cycad Encephalartos altensteinii, brought back in 1775 and often called the oldest pot plant in the world). The Princess of Wales Conservatory (opened 1987) packs ten computer-controlled climate zones under one roof, from dry desert to dripping mangrove, and is where Kew flowers its Titan arum (Amorphophallus titanum). Tie to collectors: Kew was the hub through which the tropics were collected, named, and distributed; the wet zones hold the aroids, orchids and ferns readers grow. What not to miss: the Palm House aerial walkway, the Waterlily House, the Temperate House, the Treetop Walkway. Why breathtaking: stepping into a Victorian iron cathedral fogged with palm-house humidity. Keep every date, name and figure accurate; do not invent statistics or quotes."},
 {"slug":"conservatory-eden-project",
  "title":"Botanical Tour: The Eden Project Biomes, Cornwall, UK — The Largest Rainforest Under a Roof",
  "angle":"The Eden Project (opened 2001) was built inside a worked-out china-clay (kaolinite) pit near St Austell, Cornwall — a dead industrial crater reborn as a garden. Conceived by Tim Smit and designed by architect Nicholas Grimshaw, its biomes are geodesic domes clad not in glass but in giant hexagonal ETFE (foil) cushions, far lighter than glass. The Rainforest Biome is the largest indoor rainforest in the world: tall enough to hold a canopy walkway and a rope bridge high in the trees, planted with species from tropical South America, West Africa, Malaysia and Oceania. Explain how a humid, self-contained tropical world is engineered — misting, a waterfall, heat. Tie to collectors: bananas, cacao, rubber and the aroids/epiphytes climbing the biome's trees. What not to miss: the canopy walkway and the lookout, the cloud bridge, the Mediterranean Biome next door. Why breathtaking: a whole rainforest bubbling up out of a Cornish pit. Stick to verifiable facts; don't fabricate figures."},
 {"slug":"conservatory-berlin-tropenhaus",
  "title":"Botanical Tour: Berlin's Großes Tropenhaus, Germany — One of the Tallest Glass Jungles on Earth",
  "angle":"The Großes Tropenhaus (Great Tropical House) at the Botanischer Garten Berlin in Dahlem is one of the tallest and largest greenhouses in the world, a steel-and-glass vault roughly 25-26 metres high. Built 1905-1907 and comprehensively restored 2006-2009, it lets giant tropical trees, palms and bamboo grow to near-full height indoors. The Botanic Garden Berlin itself spans about 43 hectares with on the order of 20,000 plant species, making it one of the largest botanical gardens anywhere. Explain what that vertical height allows — a true multi-storey jungle with a canopy, not a low glasshouse. Tie to collectors: the tropical climbers and aroids, the great fern and cycad collections, the herbarium's scientific weight. What not to miss: the height of the central vault, the aquatic house with giant waterlilies, the historic glasshouse complex. Why breathtaking: standing under a 26-metre glass sky filled with jungle in northern Europe. Keep facts accurate; approximate heights should be framed as approximate."},
 {"slug":"conservatory-cloud-forest-singapore",
  "title":"Botanical Tour: Gardens by the Bay — Cloud Forest, Singapore — A Mountain of Mist and Epiphytes",
  "angle":"The Cloud Forest conservatory at Gardens by the Bay (opened 2012) is built around 'Cloud Mountain', a roughly 35-metre planted tower down which pours one of the world's tallest indoor waterfalls, wreathed in cool mist. It recreates the conditions of a tropical montane cloud forest (the perpetually damp 1,000-3,000 m elevation band), so the mountain is furred with epiphytes: orchids, ferns, bromeliads, begonias, club mosses and carnivorous Nepenthes pitcher plants. Designed by architects Wilkinson Eyre with landscape by Grant Associates, it sits beside the Flower Dome, the world's largest glass greenhouse. Explain why cloud-forest plants (many of them the velvet-leaved aroids and epiphytes collectors chase) need constant cool moisture. Tie to collectors: this is the epiphyte lifestyle made walkable, on aerial Treetop and Cloud walkways. What not to miss: the waterfall from the top walkway, the crystal cave, the view of the Supertrees. Why breathtaking: a cold, misted indoor mountain in equatorial Singapore. Do not invent numbers beyond the well-established ones."},
 {"slug":"conservatory-amazon-spheres",
  "title":"Botanical Tour: The Amazon Spheres, Seattle, USA — A Collector's Cathedral in the City",
  "angle":"The Amazon Spheres (opened January 2018) are three interlocking glass domes at the heart of Amazon's downtown Seattle headquarters, designed by the architecture firm NBBJ as a workplace that is also a cloud-forest conservatory. They hold on the order of 40,000 plants of hundreds of species gathered from the cloud forests of dozens of countries, including a four-storey living green wall and 'Rubi', a roughly 55-foot Ficus rubiginosa craned in whole. A dedicated horticulture team grows and rotates the collection from an off-site greenhouse, with a real emphasis on epiphytes and rare or endangered species. Tie to collectors: this is, in effect, the collector's fantasy built at corporate scale — a living wall of rare aroids, orchids and epiphytes that people work beside. Address honestly that it is a workplace with limited public visiting days. What not to miss: the living wall, Rubi, the epiphyte-clad birdnest structure. Why breathtaking: a rare-plant biosphere dropped into a city downtown. Keep the figures to the well-documented ones."},
 {"slug":"conservatory-marie-selby",
  "title":"Botanical Tour: Marie Selby Botanical Gardens, Sarasota, USA — The World Capital of Epiphytes",
  "angle":"Marie Selby Botanical Gardens (opened to the public in 1975 on Marie Selby's bayfront estate on Sarasota Bay, Florida) is the one botanical garden in the world devoted specifically to epiphytes — the 'air plants' that grow on other plants: orchids, bromeliads, gesneriads, ferns, and aroids. It is a serious research institution, home to the Bromeliad Identification Center and one of the most scientifically important living collections of orchids and bromeliads anywhere, backed by a large herbarium and a legacy tracing to bromeliad pioneer Mulford B. Foster. Explain what an epiphyte is and why a garden would specialize in them — these are precisely the plants collectors mount on boards and grow in bright, airy setups. Tie to collectors: this is the institutional home of the exact plants in their app. What not to miss: the Tropical Conservatory, the orchid and bromeliad displays, the banyan and the bay views. Why breathtaking: a research garden on the water given over entirely to plants that live in the air. Stay factual; don't fabricate specimen counts."},
 {"slug":"conservatory-climatron",
  "title":"Botanical Tour: The Climatron, St. Louis, USA — A Geodesic Rainforest",
  "angle":"The Climatron at the Missouri Botanical Garden (opened 1960) was the first geodesic-dome greenhouse, built on Buckminster Fuller's structural principles by architects Murphy and Mackey; it won the R.S. Reynolds Memorial Award for architecture in 1961. About 175 feet across and 70 feet high with no interior supports, it encloses roughly half an acre of climate-controlled rainforest — canopy, waterfalls, orchids, epiphytes and tropical trees (it was reglazed with glass in a 1988-1990 renovation). But the deeper story for collectors is the institution around it: the Missouri Botanical Garden, founded in 1859 by Henry Shaw, is the oldest botanical garden in continuous operation in the United States and the world capital of aroid science. Its longtime curator Dr. Thomas B. Croat is the foremost authority on the Araceae, having described more aroid species — Anthurium and Philodendron above all — than anyone; the Garden's enormous herbarium and its Tropicos database are global references. Tie to collectors: the philodendrons and anthuriums people grow were, very often, named here. What not to miss: the dome's canopy and waterfalls, and the sense of the herbarium behind it. Why breathtaking: a Space-Age dome fronting the world's center of aroid taxonomy. Keep every date and name correct; do not overstate Croat's species totals with a made-up number."},
 {"slug":"conservatory-haupt-nybg",
  "title":"Botanical Tour: The Enid A. Haupt Conservatory, New York, USA — A Crystal Palace of the Tropics",
  "angle":"The Enid A. Haupt Conservatory (opened 1902) at the New York Botanical Garden in the Bronx is the grandest Victorian-style glasshouse in America — an Italian-Renaissance-inflected palace of glass built by the famed greenhouse firm Lord & Burnham, crowned by a 90-foot-tall central Palm Dome. It is a National Historic Landmark, saved from demolition and restored in 1978 with a gift from the philanthropist Enid A. Haupt (and again in the 1990s). Under its glass runs 'A World of Plants': tropical lowland and upland rainforest galleries, deserts, and aquatic and carnivorous houses. The NYBG itself (founded 1891) was consciously modeled on Kew and anchors one of the great botanical libraries and herbaria in the world. Tie to collectors: the rainforest galleries hold the palms, aroids and orchids readers grow. What not to miss: the Palm Dome, the seasonal orchid show, the Holiday Train Show. Why breathtaking: a crystal palace of the tropics at the top of Manhattan's doorstep. Keep facts verifiable."},
 {"slug":"conservatory-flowers-sf",
  "title":"Botanical Tour: The Conservatory of Flowers, San Francisco, USA — The Grand Old Glasshouse of the West",
  "angle":"The Conservatory of Flowers in Golden Gate Park (opened 1879) is the oldest wood-and-glass conservatory in North America — a luminous white Victorian structure that survived the 1906 earthquake, was nearly destroyed by a 1995 windstorm, and reopened in 2003 after a major restoration. Inside are five gallery worlds: Lowland Tropics, Highland Tropics, Aquatic Plants (with the giant Victoria waterlily), Potted Plants, and rotating Special Exhibits. The Highland Tropics gallery is the one for collectors — cool, high-elevation orchids and aroids, including venerable large philodendrons, grown in the exact cloud-cool conditions many prized houseplants come from (San Francisco's fog does the work). Tie to collectors: highland aroids and orchids are the heart of the hobby, and this is a place to see them mature and enormous. What not to miss: the Highland Tropics gallery, the giant waterlily, the glowing dome lit at night. Why breathtaking: the West's grand old glasshouse, still standing through quakes and storms. Keep facts accurate."},
 {"slug":"conservatory-ntbg-kauai",
  "title":"Botanical Tour: The National Tropical Botanical Garden, Kauai, USA — America's Rarest Tropical Plants",
  "angle":"The National Tropical Botanical Garden (chartered by the U.S. Congress in 1964) is the country's premier tropical plant research and conservation institution, headquartered on Kauai, Hawaii. It is a network of gardens — McBryde and Allerton in Kauai's Lawai Valley, Limahuli on Kauai's north shore, Kahanu on Maui, and The Kampong in Florida — and it holds one of the world's largest living collections of rare and endangered tropical plants, a genuine ark for Hawaiian species that are extinct or nearly gone in the wild. Allerton Garden is a spellbinding designed landscape whose enormous buttressed Moreton Bay fig (Ficus macrophylla) appeared in Jurassic Park. Explain the conservation mission: seed banking, propagation, and saving island endemics from extinction. Tie to collectors: tropical palms, aroids and the ethics of rarity — why 'rare' should mean 'protected', not just 'expensive'. What not to miss: the Allerton fig and water gardens, the Lawai Valley, the endangered-species collections. Why breathtaking: the most important tropical-plant rescue garden in America, in a Kauai valley. Keep facts accurate."},
 {"slug":"conservatory-hawaii-tropical",
  "title":"Botanical Tour: Hawaii Tropical Botanical Garden, Big Island, USA — A Rainforest Valley on the Sea",
  "angle":"The Hawaii Tropical Botanical Garden is a nonprofit nature preserve in Onomea Valley on the Hamakua Coast just north of Hilo on Hawaii's Big Island, created by Dan and Pauline Lutkenhouse and opened to visitors in 1984. It is set in a wild valley that tumbles down to the Pacific at Onomea Bay: boardwalk trails wind through a genuine tropical rainforest past waterfalls (including Onomea Falls), streams and a sea-cliff coastline, planted with well over a thousand species. Its collections lean into exactly the plants that photograph like a dream — heliconias, gingers, orchids, bromeliads, palms and aroids. Explain how a natural ocean-front valley became a curated tropical garden without losing its wildness. Tie to collectors: heliconias, anthuriums and aroids thriving outdoors in true tropical conditions. What not to miss: the boardwalk to the ocean overlook, Onomea Falls, the palm and heliconia collections. Why breathtaking: a rainforest garden pouring straight into the sea, arguably one of the most beautiful garden settings on Earth. Keep facts accurate; frame species counts as approximate."},
 {"slug":"conservatory-nong-nooch",
  "title":"Botanical Tour: Nong Nooch Tropical Botanical Garden, Pattaya, Thailand — Cycads, Palms, and Spectacle",
  "angle":"Nong Nooch Tropical Botanical Garden, southeast of Pattaya, Thailand (opened to the public around 1980), is one of the largest and most elaborate tropical gardens in Southeast Asia, sprawling across roughly 500 acres. Behind the theatrical themed gardens and daily cultural shows sits something scientifically serious: one of the world's largest ex-situ collections of cycads and a globally significant palm collection, making it a real conservation resource for two of the most ancient and threatened plant lineages. Explain what cycads are — living relics from the age of the dinosaurs, slow-growing and heavily trafficked, hence the value of a great living collection. Tie to collectors: palms, cycads and the aroids of the Thai tropics, plus the tension between spectacle and serious botany. What not to miss: the cycad and palm valleys, the vast tropical plantings, the orchid displays. Why breathtaking: a half-square-kilometre of tropical showmanship that doubles as one of the planet's great cycad arks. Keep the acreage and facts to well-documented figures."},
 {"slug":"conservatory-rio-de-janeiro",
  "title":"Botanical Tour: Jardim Botânico do Rio de Janeiro, Brazil — Imperial Palms and the Atlantic Forest",
  "angle":"The Jardim Botânico do Rio de Janeiro was founded in 1808 by the Portuguese Prince Regent (the future King João VI), which makes it one of the oldest botanical gardens in the Americas. Its signature is the Avenue of Royal Palms — a cathedral-like avenue of towering royal palms (Roystonea) descended from a single original tree, the 'Palma Mater'. The garden holds thousands of species across its grounds, an orchidarium, a bromeliad house, and — crucially for this series — a surviving fragment of the Atlantic Forest (Mata Atlântica) climbing the slopes beneath Christ the Redeemer on Corcovado. Explain why that matters: the Atlantic Forest is the shredded, hyper-endemic biome that gives collectors many of their Brazilian Philodendron, Anthurium and begonias, and here it meets a working research garden. Tie to collectors: this is the Neotropical heart of the tour, the region behind so many prized aroids. What not to miss: the royal palm avenue, the orchidarium, the Atlantic-Forest trail and the views. Why breathtaking: 200-year-old palm avenues at the foot of Christ the Redeemer, on the edge of a vanishing forest. Keep facts accurate."},
 {"slug":"conservatory-adelaide",
  "title":"Botanical Tour: The Bicentennial Conservatory, Adelaide, Australia — The Southern Hemisphere's Great Span",
  "angle":"The Bicentennial Conservatory in the Adelaide Botanic Garden (opened 1989, designed by architect Guy Maron to mark Australia's bicentenary) is the largest single-span glasshouse in the Southern Hemisphere — a soaring, curved arc of steel and glass, on the order of 100 metres long and around 27 metres high, with an elevated walkway and a misting system. It shelters lowland tropical rainforest, with a deliberate emphasis on endangered species from northern Australia, New Guinea and the nearby Pacific islands — a conservation collection as much as a display. Explain how a single vast arc creates a humid tropical world in a dry-climate city, and why saving lowland-rainforest species matters as those forests fall. Tie to collectors: the aroids and rainforest plants of Australasia and the Melanesian arc, a region collectors increasingly chase. What not to miss: the sweep of the arc from the walkway, the endangered-species plantings, the wider Adelaide Botanic Garden. Why breathtaking: a gleaming glass wave holding a slice of endangered jungle. Keep dimensions framed as approximate."},
 {"slug":"conservatory-copenhagen",
  "title":"Botanical Tour: Copenhagen's Palm House, Denmark — Iron, Glass, and a Spiral Into the Canopy",
  "angle":"The Palm House at the Botanical Garden of the University of Copenhagen (opened 1874) is a jewel of Victorian glasshouse design — a tall cast-iron-and-glass dome, its interior fitted with a slender cast-iron spiral staircase that climbs to a walkway near the roof so visitors can look down through the palm canopy. Its style consciously echoes London's Crystal Palace and Kew's Palm House. It anchors a historic complex of glasshouses in a roughly 10-hectare garden that is part of Denmark's Natural History Museum, home to old palms and cycads (some among the longest-lived potted plants in cultivation). Explain the Victorian dream this represents: bringing the equator to cold northern cities under glass and iron. Tie to collectors: palms, cycads and tropical foliage seen from above. What not to miss: the spiral staircase and the rooftop walkway, the old cycads, the connected glasshouses. Why breathtaking: climbing a wrought-iron spiral up into the palm crowns in the heart of Copenhagen. Keep facts accurate."},
 {"slug":"conservatory-bogor",
  "title":"Botanical Tour: Bogor Botanical Gardens, Java, Indonesia — Two Centuries of Tropical Obsession",
  "angle":"Kebun Raya Bogor — the Bogor Botanical Gardens in West Java, Indonesia — was founded in 1817 under Dutch colonial rule by the naturalist Caspar Reinwardt, making it one of the oldest and most historically important tropical botanical gardens in the world, spread across roughly 87 hectares beside the Presidential Palace. It was a cradle of tropical botany and agronomy in Southeast Asia (rubber, oil palm and cinchona were among the crops trialed here), and it remains a living treasury of the equatorial flora, with a historic orchid house and vast collections of palms and aroids. It is famous as a place to see the giants bloom: the Titan arum (Amorphophallus titanum, an aroid) and giant Victoria waterlilies. Tie to collectors: the Titan arum is the aroid world's pilgrimage flower, and Bogor's aroid and orchid collections are the deep tropical roots of the hobby. What not to miss: the Titan arum when it blooms, the orchid house, the two-century-old avenues and the aroid plantings. Why breathtaking: two hundred years of tropical obsession in a single equatorial garden. Keep dates and facts accurate."},
]

def build_prompt(a):
    return ("Write one article for Understory (long-form editorial, 1100-1600 words) — the depth and "
     "texture of a great magazine feature, not a blog post. This is a PLACE story about a real, famous "
     "tropical conservatory or botanical garden, told as a rounded narrative that lands on the plants "
     "our readers grow (rare aroids, epiphytes, orchids, philodendrons, anthuriums).\n"
     f"Angle / brief (all facts here are to be treated as accurate anchors): {a['angle']}\n"
     f"Category label to use: {CAT}\n"
     "CRITICAL — AUTHENTICITY: base the article ONLY on well-established, real facts about this place — "
     "its history, who built it and when, its architecture, its signature plants, why it matters. Do NOT "
     "invent statistics, dates, dimensions, species counts, awards, or quotations. If you are not sure of "
     "a precise number, describe it qualitatively instead of guessing. Never fabricate.\n"
     "Cover, woven naturally (not as a checklist): the history and the people behind it; what makes it "
     "architecturally or botanically special; why it would be breathtaking to visit; what NOT to miss; "
     "and the plants inside that connect to what collectors grow.\n"
     "Open with `intro`: 1-2 vivid scene-setting paragraphs before the first heading. Then 5-7 sections "
     "(heading + 2-4 substantial paragraphs) plus one pull quote. Use real botanical names where apt.\n"
     "meta_title = the bare headline only, no brand suffix. `body_image_caption` = a 4-9 word caption for "
     "an inset photo of a SIGNATURE PLANT one would see there (aroid/epiphyte/orchid/palm), describing "
     "only what is reliably true. `faqs` = 3-4 real questions a visitor would search about this place "
     "(hours/what to see/why famous), each a direct factual 2-4 sentence answer. Return JSON only.")

def one(a, date_str):
    art = common.generate(common.voice(), build_prompt(a), SCHEMA)
    art["title"] = a["title"]; art["category"] = CAT
    art["meta_title"] = common.strip_emphasis(common.clean_meta_title(art["meta_title"]))
    texts = [art["title"], art["deck"], art["pull_quote"], art.get("body_image_caption","")] + art.get("intro", [])
    for f in art.get("faqs", []): texts += [f["q"], f["a"]]
    for s in art["sections"]: texts += [s["heading"], *s["paragraphs"]]
    h = slop_repair.check_article(texts)
    if h: print(f"  [slop warn] {a['slug']}: {h}")
    rk = dict(hero=HERO, og_image=HERO, body_image=BODY, slug=a["slug"], hero_attribution="", body_image_attribution="", **art)
    out = common.SITE_ROOT / "the-leaf" / a["slug"]; out.mkdir(parents=True, exist_ok=True)
    (out/"index.html").write_text(render("leaf-canonical.html", gated=False, **rk), encoding="utf-8")
    (out/"preview.html").write_text(render("leaf-canonical.html", gated=True, **rk), encoding="utf-8")
    (out/"_data.json").write_text(json.dumps({**art,"slug":a["slug"],"hero":HERO,"body_image":BODY,"status":"pending"}, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    manifest_helpers.upsert(MANIFEST, {"slug":a["slug"],"title":a["title"],"category":CAT,
        "description":art["meta_description"],"url":f"/the-leaf/{a['slug']}","date":date_str,"thumb":HERO,"status":"pending"})
    print(f"  wrote {a['slug']}  ({date_str}, {len(art['sections'])} sec)")

def main():
    want = sys.argv[1] if len(sys.argv) > 1 else None
    for i, a in enumerate(ARTICLES):
        if want and a["slug"] != want: continue
        date_str = (START - dt.timedelta(days=i)).isoformat()   # 07-20, 07-19, ... (below rainforest 07-21)
        print(f"- {a['title']}")
        one(a, date_str)
    print("done"); return 0

if __name__ == "__main__":
    raise SystemExit(main())
