#!/usr/bin/env python3
"""Queue an Understory story for each of the 68 app plants.

One Understory feature per plant — the *story*, in a documentary/collector (Jake-style)
narrative, generated by generate_leaf.py with its existing iNat image sourcing. Status
'queued' so the cron picks them up one per run, routes through /review, and lands in
feed.json (website + app). Idempotent: skips any slug already in the Understory manifest or
queue.

Run once:  python pipeline/queue_plant_articles.py
"""

import json
from collections import defaultdict

import common

LEAF_QUEUE = common.ROOT / "leaf_queue.json"
LEAF_MANIFEST = common.SITE_ROOT / "the-leaf" / "manifest.json"
PROFILES = json.loads((common.ROOT / "profile_images.json").read_text())  # slug -> app photo

# (slug, genus, display, story_hint) — the story_hint seeds the Understory feature.
PLANTS = [
    # --- Anthurium ---
    ("anthurium-warocqueanum", "Anthurium", "Anthurium warocqueanum", "The Queen of the cloud forest: how a metre-long sheet of black velvet from the Colombian Andes became the hobby's holy grail, and the heartbreak of trying to keep her alive on a shelf."),
    ("anthurium-veitchii", "Anthurium", "Anthurium veitchii", "The King: pendant, deeply corrugated leaves that can pass two metres, the Victorian Veitch nursery that named it, and why 'narrow' versus 'wide' form starts arguments."),
    ("anthurium-crystalanium", "Anthurium", "Anthurium crystallinum", "The gateway velvet: sugar-white veins on deep green, the plant that pulls people down the rabbit hole, and the endless crystallinum-versus-clarinervium confusion."),
    ("anthurium-ace-of-spades", "Anthurium", "Anthurium 'Ace of Spades'", "The blackest leaf in the room: how a near-black anthurium became a status symbol, why most plants sold under the name aren't the real thing, and what darkness actually costs."),
    ("anthurium-papillilaminum", "Anthurium", "Anthurium papillilaminum", "The parent behind half the dark hybrids: a papillate-leaf Panamanian velvet, the breeders who chase its genes, and the provenance obsession around 'true' papi."),
    ("anthurium-dressleri", "Anthurium", "Anthurium dressleri", "The Panamanian grail named for a legendary botanist: bullet-dark, bullate, and so tied to provenance that collectors trade lineage like baseball cards."),
    ("anthurium-forgetii", "Anthurium", "Anthurium forgetii", "The plant with no lobes: a perfectly round, peltate leaf rimmed in bone-white veins, and why a leaf shape this clean feels almost engineered."),
    ("anthurium-cutucuence", "Anthurium", "Anthurium cutucuense", "From the Cordillera del Cóndor: a rippling cloud-forest drape discovered in one of Ecuador's most remote ranges, and what 'locality' means to a collector."),
    ("anthurium-regale-story-placeholder", "Anthurium", "Anthurium regale", ""),  # placeholder removed below
    ("anthurium-corrugatum", "Anthurium", "Anthurium corrugatum", "Texture as the whole point: an Ecuadorian species so puckered and quilted the surface becomes a landscape, and why bullate leaves photograph like nothing else."),
    ("anthurium-vittariifolium", "Anthurium", "Anthurium vittariifolium", "The ribbon: pendant strap leaves a metre long and hot-pink berries — the chandelier anthurium that looks like no houseplant should."),
    ("anthurium-wendlingeri", "Anthurium", "Anthurium wendlingeri", "Velvet on a string: long pendant ribbons and a corkscrew spadix from Costa Rica and Panama, and the misting-or-die reputation that scares people off."),
    ("anthurium-morona", "Anthurium", "Anthurium morona", "Out of Morona-Santiago: a deep-jungle Ecuadorian velvet most collectors have never seen, and the thrill of a species still flying under the radar."),
    ("anthurium-kunayalense", "Anthurium", "Anthurium kunayalense", "Named for Guna Yala: a Panamanian species carrying the name of the indigenous comarca it comes from, and what naming a plant for a homeland means."),
    ("anthurium-antolakii", "Anthurium", "Anthurium antolakii", "The sleeper: a quiet velvet collectors overlook, named for a modern grower — a window into how new anthuriums get described and named today."),
    ("anthurium-cupulispathum", "Anthurium", "Anthurium cupulispathum", "Deep-cut rarity: the cup-spathe species you only meet once you're far down the rabbit hole, and the appeal of plants nobody at the party will recognize."),
    ("anthurium-carla-blackie", "Anthurium", "Anthurium 'Carla Blackie'", "When a hybrid gets a human name: the dark cross behind the label, how named anthurium hybrids carry breeder lineages, and why a name can move a price."),
    ("anthurium-dark-mama", "Anthurium", "Anthurium 'Dark Mama'", "Bred for darkness: the hybrid arms race to grow an ever-blacker leaf, what 'Dark Mama' actually is, and the strange economics of engineered rarity."),
    # --- Philodendron ---
    ("philodendron-spiritus-sancti", "Philodendron", "Philodendron spiritus-sancti", "The ghost of Espírito Santo: a Brazilian philodendron believed down to a handful of wild plants, the most coveted leaf in the hobby, and a conservation story disguised as a flex."),
    ("philodendron-gloriosum", "Philodendron", "Philodendron gloriosum", "The crawler: a velvet heart with white veins that refuses to climb, the rhizome that wants to walk across the pot, and why everyone gets the planting wrong."),
    ("philodendron-melanochrysum", "Philodendron", "Philodendron melanochrysum", "Black gold: the drip-tip velvet climber that turns from juvenile to giant when it finds a pole, and the melano-versus-micans gateway story."),
    ("philodendron-gigas", "Philodendron", "Philodendron gigas", "The giant of Panama: a velvet leaf that ages from copper to near-black and gets enormous, and what 'gigas' really demands in return."),
    ("philodendron-verrucosum", "Philodendron", "Philodendron verrucosum", "Hairy petioles and stained-glass leaves: the iridescent Ecuadorian climber that's equal parts gorgeous and dramatic, and why it sulks the second the air dries out."),
    ("philodendron-pink-princess", "Philodendron", "Philodendron 'Pink Princess'", "The variegation lottery: how a bubblegum-pink philodendron became a viral status plant, the reversion heartbreak, and the 'Pink Congo' scam that burned thousands."),
    ("philodendron-white-knight", "Philodendron", "Philodendron 'White Knight'", "Dark stems, white leaves: the high-contrast variegate collectors covet, the slow climb, and the patience tax on a chimeric plant that can't be rushed."),
    ("philodendron-billietiae", "Philodendron", "Philodendron billietiae", "Tangerine petioles: the orange-stemmed strap climber from the Guiana Shield, its seasonal flush rhythm, and the variegated form that broke the bank."),
    ("philodendron-tortum", "Philodendron", "Philodendron tortum", "Living sculpture: skeletal, twisting, finger-thin leaflets that look more like a fossil than foliage — the jungle's idea of minimalism."),
    ("philodendron-squamiferum", "Philodendron", "Philodendron squamiferum", "Touch the stem: fuzzy red-bristled petioles holding up oak-leaf foliage, and the case that half an aroid's beauty is the parts that aren't the leaf."),
    ("philodendron-florida-ghost", "Philodendron", "Philodendron 'Florida Ghost'", "Ghost leaves: new growth that emerges ghostly white and ages to green, the hybrid lineage behind it, and the 'how white will it stay' gamble."),
    ("philodendron-paraiso-verde", "Philodendron", "Philodendron 'Paraiso Verde'", "The marbled mystery: a plant whose very origins and identity collectors still argue about, and what it means to love a plant nobody can place."),
    ("philodendron-strawberry-shake", "Philodendron", "Philodendron 'Strawberry Shake'", "Pink, cream and green confetti: the flushed new growth that sells the plant, the variegation that fades, and chasing that one perfect leaf."),
    ("philodendron-jose-buono", "Philodendron", "Philodendron 'Jose Buono'", "Big paddles, bold splashes: the large-leaf variegate, the stability that makes it a grower favorite, and the joy of a variegated plant that doesn't betray you."),
    ("philodendron-orange-marmalade", "Philodendron", "Philodendron 'Orange Marmalade'", "Citrus on a leaf: the orange-variegated hybrid, how new leaves blaze and settle, and the warm-tone variegation niche collectors are only now chasing."),
    ("philodendron-blizzard", "Philodendron", "Philodendron 'Blizzard'", "Snow on green: a frosty white-variegated hybrid, where it sits in the white-philodendron family tree, and the look-alike maze of named whites."),
    ("philodendron-green-congo-nuclear", "Philodendron", "Philodendron 'Green Congo Nuclear'", "Neon, on purpose: the electric chartreuse Congo, how a tissue-culture color sport gets a name, and the line between cultivar and marketing."),
    ("philodendron-burle-marx-variegata", "Philodendron", "Philodendron 'Burle Marx Variegata'", "Named for a landscape legend: the variegated form of a workhorse philodendron, Roberto Burle Marx's shadow over plant culture, and variegation done tastefully."),
    ("philodendron-lynnhannoniae", "Philodendron", "Philodendron lynnhannoniae", "A species, not a cultivar: the rare true-species philodendron most people have never heard of, and why species snobbery exists in a hybrid-soaked hobby."),
    ("philodendron-heartleaf", "Philodendron", "Philodendron hederaceum", "The everyplant with a secret: the humble heartleaf in every dorm room is the same genus as the grails — a love letter to the plant that started most of us."),
    # --- Monstera ---
    ("monstera-thai-constellation", "Monstera", "Monstera 'Thai Constellation'", "A galaxy grown in a lab: the tissue-cultured variegated deliciosa from Thailand that democratized a status plant, and what stable variegation really changed."),
    ("monstera-albo-variegata", "Monstera", "Monstera deliciosa 'Albo'", "The half-moon that started it all: the unstable white-variegated deliciosa, the cutting economy it spawned, and the reversion anxiety baked into every node."),
    ("monstera-obliqua", "Monstera", "Monstera obliqua", "More hole than leaf: the ghost everyone mistakes for adansonii, the Peru form myth, and the most misidentified plant in the entire hobby."),
    ("monstera-aurea", "Monstera", "Monstera deliciosa 'Aurea'", "Variegation in gold: the marbled-yellow deliciosa, why aurea behaves differently from albo, and the chase for that perfect mustard-and-green leaf."),
    ("monstera-dubia", "Monstera", "Monstera dubia", "The shapeshifter: a shingling juvenile that hugs bark flat as a coin, then transforms into something unrecognizable — the most dramatic glow-up in aroids."),
    ("monstera-burle-marx-flame", "Monstera", "Monstera 'Burle Marx Flame'", "Fenestration like fire: the flame-shaped windows that set this form apart, the Burle Marx name again, and how leaf 'cutting' patterns become identity."),
    ("monstera-siltepecana", "Monstera", "Monstera siltepecana", "Silver to swiss-cheese: the dusty blue-silver juvenile that fenestrates as it climbs, and the El Salvador form that collectors pay up for."),
    ("monstera-pinnatipartita", "Monstera", "Monstera pinnatipartita", "The climber that splits: solid juvenile leaves that tear into deep pinnate fingers once they catch a pole — patience as a feature, not a bug."),
    ("monstera-adansonii-variegata", "Monstera", "Monstera adansonii variegata", "Holes plus cream: the variegated swiss-cheese, the Indonesian versus round forms, and why 'adansonii' covers more plants than people think."),
    ("monstera-standleyana-variegata", "Monstera", "Monstera standleyana 'Albo'", "Not even a true Monstera question: the dark glossy climber with paint-splatter variegation, the albo-versus-aurea split, and an underrated easy variegate."),
    ("monstera-mint", "Monstera", "Monstera 'Mint'", "The mint unicorn: a green-on-green variegated deliciosa so rare and unstable it's almost myth, and the line between a real cultivar and a fever dream."),
    # --- Hoya ---
    ("hoya-callistophylla", "Hoya", "Hoya callistophylla", "Stained glass: leaves veined in dark leading like a cathedral window, the Borneo origin, and the case that hoyas are the most underrated leaf show in the hobby."),
    ("hoya-kerrii", "Hoya", "Hoya kerrii", "The sweetheart con: how a single rootless leaf became a Valentine's gimmick that will never grow — and the real vining sweetheart plant underneath the myth."),
    ("hoya-linearis", "Hoya", "Hoya linearis", "A waterfall of fuzz: the soft, needle-leaved Himalayan cliff-dweller that grows like green hair, and why it hates exactly what most hoyas love."),
    ("hoya-obovata", "Hoya", "Hoya obovata", "Round, splashed, forgiving: the silver-flecked workhorse that flowers like clockwork, and the gateway hoya that turns houseplant people into hoya people."),
    ("hoya-pubicalyx", "Hoya", "Hoya pubicalyx", "The fast bloomer: speckled leaves and dark star flowers on a near-indestructible vine, and the 'Black Dragon' versus 'Royal Hawaiian' naming circus."),
    ("hoya-krimson-queen", "Hoya", "Hoya carnosa 'Krimson Queen'", "Variegation on the edges: the cream-margined carnosa, its mirror-image sibling, and the Queen-versus-Princess confusion that trips up every new collector."),
    ("hoya-krimson-princess", "Hoya", "Hoya carnosa 'Krimson Princess'", "Variegation from the inside out: the center-variegated carnosa, the pink new growth, and how one species spun off a whole family of named sports."),
    ("hoya-australis-lisa", "Hoya", "Hoya australis 'Lisa'", "Easy, fast, golden: the variegated australis that grows like it means it, and the argument that a 'beginner' hoya can still be a stunner."),
    ("hoya-kentiana-variegata", "Hoya", "Hoya kentiana variegata", "Ribbons of cream: the slender trailing wax plant in variegated dress, the wayetii confusion, and the pleasure of a hoya that just cascades."),
    ("hoya-hindu-rope", "Hoya", "Hoya carnosa 'Compacta'", "The curled classic: the contorted 'Hindu Rope' your grandmother grew, the mutation that twists every leaf, and why a 'common' plant can still be strange."),
    # --- Begonia ---
    ("begonia-maculata", "Begonia", "Begonia maculata", "Polka dots that went viral: the angel-wing begonia Instagram made famous, the silver-spotted wings, and the truth about how easy it really is."),
    ("begonia-rex-escargot", "Begonia", "Begonia 'Escargot'", "A spiral you can grow: the snail-shell rex that looks computer-generated, the painterly world of rex hybrids, and humidity as the whole ballgame."),
    ("begonia-venosa", "Begonia", "Begonia venosa", "Felted and strange: a fuzzy, succulent-leaved begonia with papery stipules built for a dry Brazilian scrub — the begonia that breaks the begonia rules."),
    ("begonia-ferox", "Begonia", "Begonia ferox", "The fierce one: a Chinese species studded with black-tipped bullate spikes, discovered shockingly recently, and the appeal of a leaf that looks armored."),
    ("begonia-listada", "Begonia", "Begonia listada", "The velvet chevron: a deep green leaf split by a single bright stripe, the herringbone texture, and the quiet elegance of a species over a hybrid."),
    ("begonia-paulensis", "Begonia", "Begonia paulensis", "Seersucker leaves: a heavily bullate Brazilian with puckered, glossy foliage and a ruffled edge, and why texture-first begonias are having a moment."),
    ("begonia-rex-fireworks", "Begonia", "Begonia 'Fireworks'", "Silver and plum explosion: the rex cultivar that earns its name, how rex color is 'painted' by leaf structure, and chasing the most electric leaf."),
    ("begonia-rex-mclauchlan", "Begonia", "Begonia 'Mclauchlan'", "A painter's begonia: swirled silver and burgundy on a classic rex, the named-cultivar culture in begonias, and the care that keeps the color."),
    ("begonia-caravan", "Begonia", "Begonia 'Caravan'", "Pattern on pattern: a bold rex-type hybrid bred purely for the leaf, the world of begonia breeders, and why nobody grows these for the flowers."),
    ("begonia-dinhdui", "Begonia", "Begonia 'Dinh Dui'", "Out of Vietnam: a striking Southeast Asian begonia and a window into the region's staggering, still-being-described begonia diversity."),
]
# drop the placeholder regale entry (regale already has a guide; not an app plant slug)
PLANTS = [p for p in PLANTS if p[3]]


def existing_slugs(manifest_path):
    try:
        return {x["slug"] for x in json.loads(manifest_path.read_text())}
    except Exception:
        return set()


def main():
    leaf_q = json.loads(LEAF_QUEUE.read_text())
    leaf_have = existing_slugs(LEAF_MANIFEST) | {x["slug"] for x in leaf_q}

    # round-robin interleave by genus so the cron output varies day to day
    by_genus = defaultdict(list)
    for slug, genus, display, story in PLANTS:
        by_genus[genus].append((slug, genus, display, story))
    order, pools = [], list(by_genus.values())
    while any(pools):
        for pool in pools:
            if pool:
                order.append(pool.pop(0))

    added = skipped = 0
    for slug, genus, display, story in order:
        if slug in leaf_have:
            skipped += 1
            continue
        entry = {"category": genus, "slug": slug, "title_hint": story, "status": "queued"}
        hero = PROFILES.get(slug)
        if hero:
            entry["hero"] = hero            # app photo as hero (all 68)
            entry["body_fallback"] = hero   # body prefers free stock; app photo only if none found
        leaf_q.append(entry)
        leaf_have.add(slug); added += 1

    LEAF_QUEUE.write_text(json.dumps(leaf_q, indent=2, ensure_ascii=False) + "\n")
    print(f"Understory stories queued: {added} (skipped {skipped} already present)")
    print(f"leaf_queue total now: {len(leaf_q)}")


if __name__ == "__main__":
    main()
